eval "$(mise activate zsh)"

if [[ -f "$HOME/.zshrc.local" ]]; then
    source "$HOME/.zshrc.local"
fi

source <(fzf --zsh)

eval "$(starship init zsh)"

eval "$(zellij setup --generate-auto-start zsh)"

export EDITOR="nvim"
export VISUAL="nvim"

# auto complete for git
autoload -Uz compinit && compinit

alias gaa='git add .'
alias ga='git add'
alias gaaa='git add --all'
alias gau='git add --update'
alias gb='git branch'
alias gbd='git branch --delete '
alias gc='git commit'
alias gcm='git commit --message'
alias gcf='git commit --fixup'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcor='git checkout release'
alias gd='git diff'
alias gda='git diff HEAD'
alias gi='git init'
alias glg='git log --graph --oneline --decorate --all'
alias gld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gm='git merge --no-ff'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gmom='git merge origin master'
alias gp='git pull'
alias gph='git push'
alias gpho='git push --set-upstream origin'
alias gpr='git pull --rebase'
alias gr='git rebase'
alias grom='git rebase origin master'
alias gs='git status'
alias gss='git status --short'
alias gst='git stash'
alias gsta='git stash apply'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash save'
alias co='code .'

alias lzg='lazygit'

alias vim='nvim'
alias vimf='vim $(fd . ~/development | fzf)'
alias vimff='vim $(fzf)'
alias reload='source ~/.zshrc'


# must go at the end of file
eval "$(zoxide init zsh)"
